export interface Course {
  id: number;
  title: string;
  imageSrc: string;
  units?: Unit[];
}

export interface ChallengeOption {
  id: number;
  courseId: string;
  challengeId: number;
  text: string;
  correct: boolean;
  imageSrc: string;
  audioSrc: string;
  challenge: Challenge;
}

export interface Challenge {
  id: number;
  lessonId: number;
  courseId: string;
  type: 'SELECT' | 'ASSIST';
  question: string;
  order: number;
  challengeOptions?: ChallengeOption[];
  lesson: Lesson;
}

export interface Lesson {
  id: number;
  courseId: string;
  title: string;
  unitId: number;
  Unit: Unit;
  order: number;
  challenges?: Challenge[];
}

export interface Unit {
  id: number;
  title: string;
  description: string;
  courseId: number;
  order: number;
  course: Course;
}

export interface Media {
  id: number;
  name: string;
  type: 'AUDIO' | 'IMAGE';
  src: string;
}

// Generated by https://quicktype.io

export interface Staff {
  id: number;
  userId: string;
  role: 'ADMIN' | 'STAFF';
  createdAt: string;
  updatedAt: string;
  user: User;
  permission: Permission[];
}

export interface Permission {
  id: number;
  createdAt: string;
  updatedAt: string;
  courseId: number;
  staffId: number;
}

export interface User {
  id: string;
  firstName: string;
  lastName: string;
  userName: string;
  avatarUrl: string;
  email: string;
  createdAt: string;
  updatedAt: string;
}
