// Generated by https://quicktype.io

export interface User {
  id: string,
  userName: string,
  email: string,
  avatarUrl: string,
  userProgress?: UserProgress
}

export interface UserProgress {
  id: number;
  userId: string;
  activeCourseId: number;
  hearts: number;
  points: number;
  activeCourse?: Course;
  user?: User
}

export interface Course {
  id: number;
  title: string;
  imageSrc: string;
  units?: Unit[]
}

export interface ChallengeProgress {
  id: number;
  userId: string;
  challengeId: number;
  completed: boolean;
}

export interface ChallengeOption {
  id: number;
  challengeId: number;
  text: string;
  correct: boolean;
  imageSrc: string;
  audioSrc: string;
}

export interface Challenge {
  id: number;
  lessonId: number;
  type: 'SELECT' | 'ASSIST';
  question: string;
  order: number;
  completed?: boolean;
  challengeProgress?: ChallengeProgress[];
  challengeOptions?: ChallengeOption[];
}

export interface Lesson {
  id: number;
  title: string;
  unitId: number;
  challenges: Challenge[];
  completed?: boolean;
}

export interface Unit {
  id: number;
  title: string;
  description: string;
  courseId: number;
  order: number;
  lessons: Lesson[];
}

export interface CourseProgress {
  activeLessonId: number;
  activeLesson: Lesson;
}

export interface UserSubscription {
  id: number;
  userId: string;
  stripeCustomerId: string;
  stripeSubscriptionId: string;
  stripePriceId: string;
  stripeCurrentPeriodEnd: string;
  isActive: boolean;
}
